[tool.uv.workspace]
members = [
  "oim/common",
  "oim/nvidia/llama-3.2-nv-embedqa-1b-v2",
  "oim/nvidia/llama-3.2-nv-rerankqa-1b-v2",
  "oim/nvidia/nemoretriever-page-elements-v3",
  "oim/nvidia/nemoretriever-graphic-elements-v1",
  "oim/nvidia/nemoretriever-table-structure-v1",
  "oim/nvidia/nemoretriever-ocr-v1",
  "oim/nvidia/nemotron-nano-12b-v2-vl",
  "oim/nvidia/parakeet-1-1b-ctc-en-us",
  "oim/baidu/paddleocr",
]

[tool.uv.sources]
oim-common = { workspace = true }
oim-llama-3-2-nv-embedqa-1b-v2 = { workspace = true }
oim-llama-3-2-nv-rerankqa-1b-v2 = { workspace = true }
oim-nemoretriever-page-elements-v3 = { workspace = true }
oim-nemoretriever-graphic-elements-v1 = { workspace = true }
oim-nemoretriever-table-structure-v1 = { workspace = true }
oim-nemoretriever-ocr-v1 = { workspace = true }
oim-nemotron-nano-12b-v2-vl = { workspace = true }
oim-parakeet-1-1b-ctc-en-us = { workspace = true }
oim-paddleocr = { workspace = true }
